version: '3'
services:
  ldl:
    # build: .
    image: vivo_113_ldl
    working_dir: /root #/home/docker #path in container
    ipc: host
    #(path/ports in host: path/ports in container)
    volumes:
      - /media/disk2/ywz/ywzvivo:/media/data/yangwenzhe
      - /media/disk2/ywz/copyccr:/media/data/ccr
      # - /media/data/minglang:/media/data/minglang
      # - /media/data/liutie:/media/data/liutie
    #   - "8000:8000"
