model: bmshj2018-hyperprior
dataset: ./feature/43_ori/
test_dataset: ./feature/43_ori/
quality: 4
lambda: 0.001
learning_rate: 1e-4
save: True
cuda: True
experiment: exp_ywz_balle_En_03_only_q4
batch_size: 1
test_batch_size: 1